server:
  port: 8080

# Primary DataSource
app.datasource.blue:
  url: jdbc:h2:mem:blue
  username: sa
  password:

app.datasource.green:
  url: jdbc:h2:mem:green
  username: sa
  password:


spring.jpa:
  database: H2
  properties.hibernate.hbm2ddl.auto: create
  properties.hibernate.format_sql: true
  properties.hibernate.use_sql_comments: true

logging.level:
  org.springframework: INFO